name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-gcc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sudo apt-get install -y qt6-base-dev qt6-declarative-dev libgl1-mesa-dev
    - name: build the app
      run: mkdir build && cd build && cmake .. && cmake --build .
